nodeLinker: node-modules

npmScopes:
  tensor-oss:
    npmAlwaysAuth: true
  tensor-hq:
    npmAlwaysAuth: true
    npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
